### ISSUE TITLE
Enhancement: Get rid of relative paths in diverse module import

### ISSUE THREAD

**Issue by c-t-n** [partz-org/mobile#3]
Some typescript files has imports with relative paths like this one:

```ts
// src/helpers/getParticipantNames.ts - L. 1
import type { Participant } from "../types/count";
```

Typescript compiler has multiple options for module resolution that you can use to transform relative paths like the one above to something more fluid like this:
```ts
import type { Participant } from "types/count";
```

You can do it by adding your src folder as `baseUrl` in the `compilerOptions` in tsconfig.json

```json
{
    "compilerOptions": {
        "baseUrl": "src"
    }
}
```

Docs here: https://www.typescriptlang.org/tsconfig#paths

**Comment by zephimir** [comment]
Thanks for the suggestion! I made #4  that fixes this issue
